app:
  build: .
  command: python3 app/manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"
  volumes:
    - .:/code
  links:
    - database
  environment:
    DB_ADAPTER: postgres
    DB_HOST: database
    DB_NAME: postgres
    DB_USER: docker
    DB_PASS: docker

database:
  image: helmi03/docker-postgis:latest
  expose:
    - 5432
