version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=testdevops
      - POSTGRES_PASSWORD=testdevops
      - POSTGRES_DB=test_devops
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
