---
- name: Instalando pacotes docker e python
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - python
  - python-pip
  ignore_errors: yes

- name: Instalando Docker
  apt:
    name: docker
  become: yes
  ignore_errors: yes

- name: Start Docker
  service:
    name: docker
    enabled: yes
    state: started
  become: yes

- name: Docker-compose install version
  pip:
    name: docker-compose
    version: 1.9.0
    state: present
